profiles/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from .views import my_profile_view

app_name = 'profiles'

urlpatterns = [
    path('', my_profile_view, name='my')
]

reports/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from .views import (
    create_report_view,
    ReportDetailView,
    ReportListView,
    render_pdf_view,
    UploadTemplateView,
    csv_upload_view,
)

app_name = 'reports'

urlpatterns = [
    path('', ReportListView.as_view(), name='main'),
    path('save/', create_report_view, name='create-report'),
    path('upload/', csv_upload_view, name='upload'),
    path('from_file/', UploadTemplateView.as_view(), name='from_file'),
    path('<pk>/', ReportDetailView.as_view(), name='detail'),
    path('<pk>/pdf/', render_pdf_view, name='pdf'),
]

reports_proj/urls.py
from django.contrib import admin
from django.contrib.auth import login
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('sales.urls', namespace='sales')),
    path('reports/',include('reports.urls', namespace='reports')),
    path('my_profile/',include('profiles.urls', namespace='profiles')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import path
from .views import (
    home_view,
    SalesListView,
    SalesDetailView,
)

app_name = 'sales'

urlpatterns = [
    path('', home_view, name='home'),
    path('sales/', SalesListView.as_view(), name='list'),
    path('sales/<pk>/', SalesDetailView.as_view(), name='detail'),
    #path('sales/<pk>/', SalesDetailView.as_view(), name='detail'),
]

sales/models.py
from django.db import models
from products.models import Product
from customers.models import Customer
from profiles.models import Profile
from django.utils import timezone
from .utils import generate_code
from django.shortcuts import reverse

# Create your models here.

class Position(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.FloatField(blank=True)
    created = models.DateTimeField(blank=True)

    def save(self, *args, **kwargs):
        self.price = self.product.price * self.quantity
        return super().save(*args, **kwargs)

    def get_sales_id(self):
        sales_obj = self.sales_set.first() #reverse relationship
        return sales_obj.id

    def get_sales_customer(self):
        sales_obj = self.sales_set.first() #reverse relationship
        return sales_obj.customer.name

    def __str__(self):
        return f"id: {self.id}, product: {self.product.name}, quantity: {self.quantity}"

class Sales(models.Model):
    transaction_id=models.CharField(max_length=12, blank=True)
    positions = models.ManyToManyField(Position)
    total_price = models.FloatField(blank=True, null=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    salesman = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created = models.DateTimeField(blank=True)
    updated = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return f"Sales for the amount of ${self.total_price}"

    def get_absolute_url(self):
        return reverse('sales:detail', kwargs={'pk': self.pk})

    def save(self,*args,**kwargs):
        if self.transaction_id == "":
            self.transaction_id = generate_code()

        if self.created is None:
            self.created = timezone.now()

        return super().save(*args,**kwargs)

    def get_positions(self,*args,**kwargs):
        return self.positions.all()

class CSV(models.Model):
    file_name = models.CharField(max_length=120, null=True)
    csv_file = models.FileField(upload_to='csvs', null=True)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.file_name)

    

sales/forms.py
from django import forms

CHART_CHOICES = (
    ('#1', 'Bar Chart'),
    ('#2', 'Pie Chart'),
    ('#3', 'Line Chart')
)

RESULT_CHOICES = (
    ('#1', 'transaction'),
    ('#2', 'sales date'),
)

class SalesSearchForm(forms.Form):
    date_from = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    date_to = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    chart_type = forms.ChoiceField(choices=CHART_CHOICES)
    results_by = forms.ChoiceField(choices=RESULT_CHOICES)

sales/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Sales
from .forms import SalesSearchForm
from reports.forms import ReportForm
import pandas as pd
from .utils import get_customer_from_id, get_salesman_from_id, get_chart, get_graph
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin



# Create your views here.

#M - Models, V - Views, T - Templates

@login_required
def home_view(request):
    sales_df=None
    positions_df = None
    merged_df = None
    df = None
    chart = None
    no_data = None
    search_form = SalesSearchForm(request.POST or None)
    report_form = ReportForm()

    
    if request.method == 'POST':
        date_from = request.POST.get('date_from')
        date_to= request.POST.get('date_to')
        chart_type = request.POST.get('chart_type')
        results_by = request.POST.get('results_by')
        #print(date_from, date_to, chart_type)

        sale_qs = Sales.objects.filter(created__date__lte=date_to, created__date__gte=date_from) #queryset lte=less than equal gte=greater than equal
        if len(sale_qs)>0:
            #obj = Sales.objects.get(id=2)
            #print(qs)
            #print(obj)
            #print(qs.values()) #list of dictionaries
            #print(qs.values_list()) #list of tuples
            #print('#########')
            sales_df = pd.DataFrame(sale_qs.values()) #we can see the column names. This is better
            sales_df['customer_id'] = sales_df['customer_id'].apply(get_customer_from_id)
            sales_df['salesman_id'] = sales_df['salesman_id'].apply(get_salesman_from_id)
            sales_df['created'] = sales_df['created'].apply(lambda x: x.strftime('%Y-%m-%d'))
            sales_df.rename({'customer_id': 'Customer', 'salesman_id': 'Salesman', 'id': 'sales_id'}, axis=1, inplace=True) #inplace, so that we don't have to write sales_df =
            #sales_df['sales_id'] = sales_df['id']
            positions_data = []

            for sale in sale_qs:
                for pos in sale.get_positions():
                    obj = {
                        'position_id': pos.id,
                        'product': pos.product.name,
                        'quantity': pos.quantity,
                        'price': pos.price,
                        'sales_id': pos.get_sales_id()
                    }
                    positions_data.append(obj)

            positions_df = pd.DataFrame(positions_data)
            merged_df = pd.merge(sales_df, positions_df, on='sales_id')

            df = merged_df.groupby('transaction_id', as_index=False)['price'].agg('sum')

            chart = get_chart(chart_type, sales_df, results_by)
            print('chart', chart)
            #print('positions df')
            #print(positions_df)

            sales_df=sales_df.to_html()
            positions_df=positions_df.to_html()
            merged_df = merged_df.to_html()
            df = df.to_html()
            
            #print('#########')
            #df2 = pd.DataFrame(qs.values_list()) #we only see numbers
            #print(df2)
        else:
            no_data = 'No Data is available in this date range!'


    context = {
       'search_form':search_form,
       'sales_df': sales_df,
       'positions_df': positions_df,
       'merged_df': merged_df,
       'df': df,
       'chart':chart,
       'report_form':report_form,
       'no_data': no_data,
    }
    return render(request, 'sales/home.html', context)

class SalesListView(LoginRequiredMixin, ListView):
    model = Sales
    template_name = 'sales/main.html'
    #context_object_name = 'qs'

class SalesDetailView(LoginRequiredMixin, DetailView):
    model = Sales
    template_name = 'sales/detail.html'

sales/templates/sales/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon --> 
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" defer></script>

    <!-- Dropzone js -->
    <link rel="stylesheet" href="{% static 'dropzone.css' %}">
    <script src="{% static 'dropzone.js' %}" defer></script>

    <!-- Custom js & css -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block scripts %}
    {% endblock scripts %}

    <title>Report app | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'sales/navbar.html' %}
    <div class="container mt-3 mb-3">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
  </body>
</html>

sales/templates/sales/detail.html
{% extends "sales/base.html" %}

{% block title %}
    detail {{object.transaction_id}}
{% endblock title %}

{% block content %}
    
<div class="row mt-3 mb-3">
    <div class="col-3">
        <img src="{{object.customer.logo.url}}" class="img-fluid" alt="{{object.customer.name}}">
    </div>
    <div class="col-9">
        <ul>
            <li>Transaction id: <b>{{object.transaction_id}}</b></li>
            <li>Salesman: <b>{{object.salesman.user.username}}</b></li>
        </ul>
    </div>
</div>

<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Product</th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>
        <th scope="col">Customer</th>
      </tr>
    </thead>
    <tbody>
        {% for pos in object.get_positions %} 
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{pos.product.name}}</td>
                <td>{{pos.quantity}}</td>
                <td>{{pos.price}}</td>
                <td>{{pos.get_sales_customer}}</td>
             </tr>

        {% endfor  %}
       
        </tbody>
    </table>
{% endblock content %}

sales/templates/sales/home.html
{% extends "sales/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block scripts %}
    <script src="{% static 'sales/home.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
hom
{% endblock title %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="reportModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add Report</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id="modal-body">
            <div id="alert-box"></div>
            <form id="report-form" autocomplete="off">
              {% csrf_token %}
              {{report_form|crispy}}
              <button type="submit" class="btn btn-info mt-2">save</button>
          </form>
        </div>
        </div>
      </div>
    </div>
  </div>

{% if no_data %}
    <div class="alert alert-warning" role="alert">
       {{no_data}} 
    </div>
{% endif%}



<form action="" method="POST">
    {% csrf_token %}
    {{search_form|crispy}}
    <button type="submit" class="btn btn-primary mt-3">search</button>

</form>
</br>
{% if sales_df %}
    sales df
    {{sales_df|safe}}
    <br>
    positions df
    {{positions_df|safe}}
    <br>
    merged df
    {{merged_df|safe}}
    <br>
    grouped by df
    {{df|safe}}
    <br>
    <img src="data:image/png;base64, {{chart|safe}}" id='img'>
    
  
{% endif %}

<br>
<button class="btn btn-primary not-visible" id="report-btn" data-bs-toggle="modal" data-bs-target="#reportModal">add report</button>

{% endblock content %}

yzP1gVzTjFd0eWpF4knCTsfbYOEkrAS6nIpR49RcwAdjDXOwv6VJwErDntspmT7J
yzP1gVzTjFd0eWpF4knCTsfbYOEkrAS6nIpR49RcwAdjDXOwv6VJwErDntspmT7J

sales/templates/sales/main.html
{% extends "sales/base.html" %}

{% block title %}
sales list
{% endblock title %}

{% block content %}
sales list 
<br>

{% for obj in object_list %}
    <div class="card mb-3">
        <a href="{{obj.get_absolute_url}}" class="card-body">{{obj.transaction_id}}</a>
    </div>
{% endfor %}

{% endblock content %}




<!--{% url 'sales:detail' obj.pk %}-->

sales/templates/sales/navbar.html
{% load static %}
{% url 'sales:home' as path_to_home %}
{% url 'sales:list' as path_to_sales %}
{% url 'reports:from_file' as path_to_from_file %}
{% url 'reports:main' as path_to_reports %}
{% url 'profiles:my' as path_to_my_profile %}




<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href=""><img src="{% static 'logo.png' %}" class="logo-sm"></a>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_home %}active{% endif %}" href="{{path_to_home}}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_sales%}active{% endif %}" href="{{path_to_sales}}">Sales</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_from_file%}active{% endif %}" href="{{path_to_from_file}}">Add from file</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_reports%}active{% endif %}" href="{{path_to_reports}}">Reports</a>
        </li>
      </ul>
    </div>
    {% if request.user.is_authenticated %}
      <div class="nav-item dropdown">
        <div class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <img src="{{request.user.profile.avatar.url}}" class="avatar-sm ">&nbsp;{{request.user}}
        </div>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <li><a class="dropdown-item {% if request.path == path_to_my_profile%}active{% endif %}" href="{{path_to_my_profile }}">Profile</a></li>
          <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
        </ul>
      </div>
    {% endif %}
  </div>
</nav>